apiVersion: v1
kind: Service
metadata:
  name: ambassador
  # So the load balancer has internal IP (rather than public IP)
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  loadBalancerSourceRanges:
  - 10.0.0.0/8 
  - 172.16.0.0/12
  - 192.168.0.0/16
  externalTrafficPolicy: Local
  ports:
   - port: 80
   # Require multiple ports if TCP routing via different port is required
   # https://www.getambassador.io/reference/tcpmappings/
   # - name: redis
   #   port: 6379
  selector:
    service: ambassador