#!/bin/sh

if [ -z "$1" ];
then echo "Usage: activate-service-account \"JSON_KEY\" (the content of .json key file)"
exit 1
fi

echo $1 > /tmp/key.json
gcloud auth activate-service-account --key-file=/tmp/key.json
rm /tmp/key.json