// Package petstore provides primitives to interact the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen DO NOT EDIT.
package petstore

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"github.com/getkin/kin-openapi/openapi3"
	"strings"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xUTW/bSAz9KwPuHrWSNikKVKcmaRAYKBqjyS3wgdXQ0hSaj85QcY1A/73g2ErsOIde",
	"CvRiGTMk3+N75DxB623wjhwnaJ4gtT1ZzH+XxPIJ0QeKbCgfGi2/9BNtGAia8wLWPlpkaMA4fv8OCoiE",
	"+tYNW2g4jlQAbwPtrqmjCFMBDi0dlYEBUzIEz8GJo3GdxDJ2GfjfSGto4J/qhW+1J1stie8lbJoE/cdo",
	"ImloHnY4+xKrqYA5TqDdaCWkRYYCtO9gdQIu5Yxbe4lvvWNssyBk0QzQAAbDhPZj2mDXUSyNh7k1uNud",
	"qYvlQt0TWihgjJLUM4emqg5ypgI0pTaawMY7aOBCpSxLTuYeWY2JkkIViBP7SAqTQqf26in2SpP1LnFE",
	"JrUm5DFSUsYp7kndBnJS6bysVQrUmrVpMUMVMJiWXMpe7IlfBGx7UmdlfUQ5NVW12WxKzNelj121z03V",
	"58XV9Ze76//Oyrrs2Q7ZNYo23a7vKD6alt7qu8ohldhjeDjUbLlvEwp4pJh2ovxf1mUtlX0gh8FAA+f5",
	"qICA3GdPKxEoj6xP2aljXa8iIWchHW1EzFmhjFZCrh2zNAstUmgtK7AbKUp86fV2HgVyGQBDGPZqVt+T",
	"oMwb9BsjuxuwY45LYvETtZbPMzk4nGvZqjzoKXgxQKDO6vpPUxPBZsy8aWm0FuP2LWXLHJD9qJ4C8UJP",
	"gtrRG7Z8JR6jk+RkXDeQ5J94cUO8JL7cLnQ2PKIlppigeXhdbvFJ+XV2l72KuTbIGksHyP3LimZaJ8IW",
	"ByKdvGyvX7Jp9VfZcEOcG/+2VUbvchPFx1mnowdo8C0OvU/cfKhrWaz5voJpNf0KAAD//y6yjuMWBgAA",
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file.
func GetSwagger() (*openapi3.Swagger, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	swagger, err := openapi3.NewSwaggerLoader().LoadSwaggerFromData(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("error loading Swagger: %s", err)
	}
	return swagger, nil
}

