version: "3.0"
services:

  server:
    image: "rancher/k3s:v1.19.4-k3s2"
    command: server --disable traefik
    tmpfs:
    - /run
    - /var/run
    privileged: true
    environment:
    - K3S_TOKEN=token
    - K3S_KUBECONFIG_OUTPUT=/output/kubeconfig
    - K3S_KUBECONFIG_MODE=666
    volumes:
    - k3s-server:/var/lib/rancher/k3s
    # This is just so that we get the kubeconfig file out
    - .:/output
    ports:
    - 6443:6443

  agent:
    image: "rancher/k3s:v1.19.4-k3s2"
    tmpfs:
    - /run
    - /var/run
    privileged: true
    environment:
    - K3S_URL=https://server:6443
    - K3S_TOKEN=token

volumes:
  k3s-server: {}
