#!/bin/bash

# A wrapper script for gcloud auth activate-service-account that takes
# in string content of service account rather than file path of the service account

if [ -z "$1" ];
then echo "Usage: activate-service-account \"JSON_KEY\" (the content of .json key file)"
exit 1
fi

echo $1 > /tmp/key.json
gcloud auth activate-service-account --key-file=/tmp/key.json
rm /tmp/key.json